services:

  postgres:
    image: postgres:16
    container_name: pg_lab2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: productsdb
    ports:
      - 5432:5432
    volumes:
      - pg_data_lab2:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d productsdb"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - lab2_network
  redis:
    image: redis:7
    container_name: redis_lab2
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 3s
    networks:
      - lab2_network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_lab2
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: productsdb
      REDIS_HOST: redis
    
    ports:
      - 9090:9090
    
    networks:
      - lab2_network

volumes:
  pg_data_lab2:

networks:
  lab2_network:
    driver: bridge