services:

  postgres:
    image: fercdevv/postgres-redis:latest
    container_name: custom_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: productsdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d productsdb"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s